pkg/api/api.go, pkg/config/config.go, scripts/deploy/autoscaler.yaml, scripts/patch-ccm.yaml
* add internal traffic in LoadBalancer
=> add internal traffic

Makefile
patch current yamls to cluster
=> add patch yaml to cluster

scripts/one-master-mode.sh
=> remove pdb for correct scaledown of worker nodes

pkg/api/api.go, pkg/api/const.go
=> add kubeconfig filemode more secure

.github/workflows/release.yml, .gitignore, .goreleaser.yml, Makefile
=> add goreleaser

.github/workflows/release.yml, go.mod, pkg/api/const.go
=> bump to go v1.17

.gitignore, Makefile, pkg/config/config.go
=> add test coverage

.golangci.yml, scripts/build-all.sh, scripts/common-install.sh, scripts/init-master.sh, scripts/post-install.sh
=> format stript files

README.md
=> fix formatting readme

README.md, pkg/config/config.go, pkg/config/const.go, scripts/chart/values.yaml, scripts/common-install.sh, scripts/post-install.sh
add nfs support for kubernetes volumes, remove default values of chart values in config file
=> add nfs support

cmd/main.go, pkg/api/api.go, pkg/config/config.go
Add `adhoc` command to execute shell command on all master nodes and workers nodes
usage:
```bash
hcloud-k8s-ctl -action adhoc -command "<some shell command>"
```
=> add adhoc command

scripts/common-install.sh
=> disable swap

scripts/common-install.sh
=> nfs fix port 111

scripts/init-master.sh, scripts/post-install.sh
=> update hcloud-init on patch

Makefile, pkg/api/api.go
=> create placementgroup only in HA mode

scripts/common-install.sh
add systemd as cgroupdriver=systemd for kubelet and docker
=> add kubelet cgroupdriver

pkg/api/api.go
=> fotmat error

scripts/chart/values.yaml
=> add latest registry image

scripts/common-install.sh
allow pull more than one image
=> disable-serializeImagePulls

scripts/upgrade-worker.sh
=> remove container is running on upgrade

scripts/upgrade-worker.sh
=> unmount nfs folders with force

scripts/upgrade-worker.sh
=> wait before umount

scripts/upgrade-worker.sh
=> stop and remove pods before mount

pkg/api/api.go, scripts/migrate-to-containerd.sh, scripts/upgrade-worker.sh
=> fix containerd migration

pkg/api/api.go, pkg/config/config.go, scripts/common-install.sh
=> install generic linux headers

pkg/api/api.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/config_test.yaml
create custom subnet CIDR for kubernetes network, for example:
```yaml
ipRange: "10.0.0.0/16"
ipRangeSubnet: "11.0.0.0/17"
```
=> create custom subnet for kubernetes

scripts/update-internal-ip.sh
script to change internal ip address on kubernetes node
=> update internal ip script

.golangci.yml
=> fix lint issues musttag

README.md, examples/config-full.yaml
=> typo readme

.github/workflows/release.yml
=> upgrade to go 1.19

scripts/chart/templates/autoscaler.yaml, scripts/chart/templates/hcloud-csi.yml, scripts/chart/templates/registry.yaml, scripts/one-master-mode.sh, scripts/post-install.sh
fix autoscaling tolleration to new kubernetes version
https://kubernetes.io/docs/reference/labels-annotations-taints/#node-role-kubernetes-io-master-taint
=> fix deprecated taint

pkg/config/config.go, pkg/config/config_test.go, pkg/config/config_test.yaml
hide tokens when printing config
=> hide secret tokens

README.md
Add information about creating cluster in US region
Closes: #63 
=> fix readme for creation US clusters

cmd/main.go, pkg/api/api.go
use context for gracefull interruption
=> add context usage

scripts/chart/templates/kube-flannel.yml
use flannel internal interface
=> fix flannel v0.20.2 settings

pkg/config/config.go, scripts/chart/templates/hcloud-csi.yml, scripts/chart/templates/metrics-server.yml, scripts/migrate-to-containerd.sh
Updated image registry host due to 
https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
=> updated registry host

.github/workflows/release.yml, Makefile
update deprecated `--rm-dist` and `--skip-validate` flags
=> update deprecated goreleaser flags

pkg/config/config.go
set autoscaling to 0 nodes in minimum to delete servers that not used
=> chore(autoscaling): set minimum nodes to 0

Makefile, scripts/common-install.sh, scripts/ubuntu-versions.sh
add command to list latest apt version of packages for kubernetes
```
make ubuntu-versions
```
=> chore(makefile): add ubuntu-versions

pkg/api/api.go
Hetzner API limits results to 25 servers to each response. For clusters with multiple servers it can be a problem
=> fix listing servers from API

.golangci.yml, cmd/main.go, go.mod, go.sum, pkg/version/version.go, pkg/version/version_test.go
check semantic version from github and application version on start, when app is not latest show info message
=> check new version on start

.golangci.yml, e2e/e2e_test.go, pkg/api/api.go, pkg/config/config.go, pkg/version/version.go
upgrade to latest golangci-lint, remove deprecated
=> golangci-lint v1.56.2

scripts/common-install.sh
allow to fail while copy to sysconfig dir
=> copy config to sysconfig allow to fail

Makefile, config.yaml, e2e/configs/full.yaml, pkg/config/config.go, scripts/common-install.sh
use ubuntu 22.04 as default version
=> use default ubuntu 22.04

pkg/config/config.go
Use additional instances for cluster autoscaler
=> add additional server instances

Makefile, scripts/chart/Chart.yaml, scripts/chart/templates/nfs-server.yaml, scripts/chart/values.yaml
use node selectors for NFS pod
=> Use NFS server selectors

.github/workflows/e2e.yml, Makefile, README.md, e2e/configs/full.yaml, e2e/configs/v1.28-amd64-ubuntu-22.04-us.yaml, e2e/configs/v1.28-arm64-ubuntu-22.04-eu.yaml, e2e/configs/v1.29-arm64-ubuntu-20.04-eu.yaml, e2e/configs/v1.29-arm64-ubuntu-22.04-eu.yaml, e2e/configs/v1.30-amd64-ubuntu-20.04-eu.yaml, e2e/configs/v1.30-amd64-ubuntu-20.04-us.yaml, e2e/configs/v1.30-amd64-ubuntu-22.04-eu.yaml, e2e/configs/v1.30-arm64-ubuntu-20.04-eu.yaml, e2e/configs/v1.30-arm64-ubuntu-22.04-eu.yaml, e2e/e2e_test.go, pkg/config/config.go, scripts/chart/Chart.lock, scripts/chart/Chart.yaml, scripts/common-install.sh, scripts/ubuntu-versions.sh
=> kubernetes 1.30

e2e/configs/v1.32-amd64-ubuntu-24.04-eu.yaml, e2e/configs/v1.32-amd64-ubuntu-24.04-us.yaml, e2e/configs/v1.32-arm64-ubuntu-24.04-eu.yaml, scripts/common-install.sh
Add support of latest Ubuntu 24.04 LTS
=> feat: Ubuntu 24.04 support
